### ISSUE TITLE
How to generate pitch_intervals and onoffset_intervals for my own test data

### ISSUE THREAD

**Issue by pratikshaya** [B05901022/Note-Segmentation-SSL#3]
I am trying to make my own testing dataset same like you did in NOte-Segmentation-SSL. Each wave file in your testing datasets ( eg. ISMIR2014, DALI, DALI_demucs, and CMedia_demucs) has its corresponding onoffset_intervals, pitch, pitch_intervals, and sdt. I successfully generate the binary sdt file. However, In your Patch-CNN repo ( https://github.com/leo-so/VocalMelodyExtPatchCNN  ) I can't able to get onoffset_intervals and pitch_intervals.  Can you please tell me how to get this for my own dataset?

**Comment by B05901022** [comment]
For testing labels, you can directly extract them from the ground truth MIDI information, which `onoffset_intervals` will be a (#MIDI Notes, 2) shaped numpy array in the form of `(onset_time, offset_time)` in seconds, and `pitch_intervals` will be a (#MIDI Notes,) shaped numpy array in the form of `(Hz)`.
For usage of Patch-CNN, the workflow is wrapped up [here][VOCANO Feature Extraction]. However, since Patch-CNN is a pretrained network for F0 estimation, it should not be used in supervised label construction.

[VOCANO Feature Extraction]: https://github.com/B05901022/VOCANO/blob/main/vocano/utils/feature_extraction_cp.py#L221

**Comment by WeiShi78** [comment]
Hi,
How can I generate the pitch labels if Patch-CNN cannot be used in supervised label construction? I noticed that in your dataset the length of pitch file is the same as sdt files. Do you use scipy.wavfile.read() with some specific sampling frequency and take the average? Or do you use the ground truth midi information and reshape it to the same length as the sdt files?

**Comment by B05901022** [comment]
Hi,

We are using 0.02 sec intervals for sdt and pitch labels (something like [this](https://github.com/B05901022/Note-Segmentation-SSL/issues/1)). That is, the length will be $\lceil \frac{AudioLength}{SampleRate\times 0.02} \rceil$. The $AudioLength$ is decided by the audio file (`scipy.io.wavfile.read()`). The pitch labels of DALI are from the ground truth midi information with something like:
```python
entry = ... # Read from DALI with filename
audio, sr = scipy.io.wavfile.read(filename)
audio = audio.astype(np.float32)
audio_length = math.ceil(audio.shape[0]/sr/0.02)-1
pitch = np.zeros((audio_length,))

for single_note in entry.annotations['annot']['notes']:
    onset, offset = single_note['time']
    freq = np.mean(single_note['freq'])
    onset, offset = round(onset*50), round(offset*50) # /0.02 == *50
    pitch[max(0,onset): min(offset, audio_length)-1] = freq
    
# pitch is the final result
```

Hope this helps!
